# Generated by Django 2.2.6 on 2019-11-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=50, unique=True, verbose_name='User Name')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_customer', models.BooleanField(default=False, verbose_name='User is Customer')),
                ('is_tailor', models.BooleanField(default=False, verbose_name='User is Tailor')),
                ('is_master', models.BooleanField(default=False, verbose_name='User is Master')),
                ('is_maggam_designer', models.BooleanField(default=False, verbose_name='User is Maggam Designer')),
                ('is_fashion_designer', models.BooleanField(default=False, verbose_name='User is Fashion Designer')),
                ('is_boutique', models.BooleanField(default=False, verbose_name='User is Boutique')),
                ('is_admin', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'managed': True,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(default='', max_length=50)),
                ('address_line_2', models.CharField(max_length=50, null=True)),
                ('landmark', models.CharField(max_length=50, null=True)),
                ('postalCode', models.IntegerField(null=True)),
                ('latitude', models.FloatField(max_length=20, null=True)),
                ('longitude', models.FloatField(max_length=20, null=True)),
                ('geoAddress', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
            options={
                'verbose_name': 'Tailor',
                'verbose_name_plural': 'tailors',
                'db_table': 'tailor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
            options={
                'verbose_name': 'master',
                'verbose_name_plural': 'masters',
                'db_table': 'master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaggamDesigner',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
            options={
                'verbose_name': 'maggamDesigner',
                'verbose_name_plural': 'maggamDesigners',
                'db_table': 'maggamDesigner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FashionDesigner',
            fields=[
                ('firmName', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
            options={
                'verbose_name': 'fashionDesigner',
                'verbose_name_plural': 'fashionDesigners',
                'db_table': 'fashionDesigner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ManyToManyField(to='users.Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'boutiques',
                'db_table': 'boutique',
                'managed': True,
            },
        ),
    ]
