# Generated by Django 2.2.7 on 2019-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.UserType'),
        ),
    ]
