# Generated by Django 2.2.7 on 2019-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypes',
            name='value',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('tailor', 'TAILOR'), ('boutique', 'BOUTIQUE'), ('master', 'MASTER'), ('mag_designer', 'MAGGAM_DESIGNER'), ('fash_designer', 'FASHION_DESIGNER')], default='customer', max_length=1),
        ),
    ]
