# Generated by Django 2.2.7 on 2019-11-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kimage',
            table='knit_image',
        ),
    ]
