# Generated by Django 2.2.7 on 2019-11-21 20:18

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=254, null=True, quality=75, size=[800, 600], upload_to=users.models.nameFile),
        ),
    ]
