# Generated by Django 2.2.7 on 2019-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.File'),
        ),
    ]
