# Generated by Django 2.2.6 on 2019-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191030_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='geoAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postalCode',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='boutique',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='shopName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
        migrations.AddField(
            model_name='designer',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='shopName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tailor',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
        migrations.AddField(
            model_name='tailor',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tailor',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='shopName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
