# Generated by Django 2.2.7 on 2019-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191109_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('tailor', 'TAILOR'), ('boutique', 'BOUTIQUE'), ('master', 'MASTER'), ('mag_designer', 'MAGGAM_DESIGNER'), ('fash_designer', 'FASHION_DESIGNER')], default='customer', max_length=80),
        ),
    ]
