# Generated by Django 2.2.7 on 2019-11-21 20:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191122_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.nameFile),
        ),
    ]
