# Generated by Django 2.2.7 on 2019-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191109_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTypes',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN'), ('leader', 'LEADER'), ('superAdmin', 'SUPERADMIN'), ('guest', 'GUEST')], default='guest', max_length=80),
        ),
    ]
