# Generated by Django 2.2.7 on 2019-11-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191113_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='isOpen',
            new_name='is_open',
        ),
        migrations.RenameField(
            model_name='tailor',
            old_name='isWeekdays',
            new_name='is_weekdays',
        ),
        migrations.RenameField(
            model_name='tailor',
            old_name='isWeekends',
            new_name='is_weekends',
        ),
    ]
