# Generated by Django 2.2.6 on 2019-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191030_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.IntegerField(null=True),
        ),
    ]
