# Generated by Django 2.2.6 on 2019-11-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191103_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(default=False),
        ),
    ]
