# Generated by Django 2.2.7 on 2019-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191109_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('SUPER_ADMIN', 'SUPER ADMIN'), ('GUEST', 'GUEST'), ('DEL_BOY', 'DELIVERY BOY')], default='GUEST', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('TAILOR', 'TAILOR'), ('BOUTIQUE', 'BOUTIQUE'), ('MASTER', 'MASTER'), ('MAGGAM_DESIGNER', 'MAGGAM DESIGNER'), ('FASHION_DESIGNER', 'FASHION DESIGNER')], default='CUSTOMER', max_length=80),
        ),
    ]
