# Generated by Django 2.2.7 on 2019-11-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='UserType',
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'managed': True, 'verbose_name': 'user_type', 'verbose_name_plural': 'user_types'},
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='role_type',
            new_name='user_type',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_type',
        ),
    ]
