# Generated by Django 2.2.7 on 2019-11-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Images',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image source'),
        ),
    ]
