# Generated by Django 2.2.7 on 2019-11-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Images',
        ),
    ]
