# Generated by Django 2.2.7 on 2019-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191114_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='masters_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
