# Generated by Django 2.2.7 on 2019-11-09 19:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.nameFile)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
