# Generated by Django 2.2.7 on 2019-11-13 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tailor_masters_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='alternate_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_weekdays',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_weekends',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='masters_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='fashiondesigner',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fashiondesigner',
            name='working_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maggamdesigner',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maggamdesigner',
            name='working_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='available_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='can_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='is_emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='working_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='is_emergency_available',
            field=models.BooleanField(default=False),
        ),
    ]
