# Generated by Django 2.2.7 on 2019-11-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191110_0115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFile',
            new_name='File',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
