# Generated by Django 2.2.7 on 2019-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
