# Generated by Django 2.2.7 on 2019-11-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191110_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.CharField(blank=True, default='customer', max_length=50, null=True),
        ),
    ]
