# Generated by Django 2.2.7 on 2019-11-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191110_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
    ]
