# Generated by Django 2.2.7 on 2019-11-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
