# Generated by Django 2.2.7 on 2019-11-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='myfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
    ]
