# Generated by Django 2.2.7 on 2019-11-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_tailor_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='myfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='myfiles', to='users.File'),
        ),
    ]
