# Generated by Django 2.2.7 on 2019-11-10 11:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191110_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image_path',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.nameFile),
        ),
        migrations.AddField(
            model_name='customer',
            name='image_size',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
