# Generated by Django 2.2.7 on 2019-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191110_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
