# Generated by Django 2.2.7 on 2019-11-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191110_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image_size',
        ),
    ]
