# Generated by Django 2.2.7 on 2019-11-10 12:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191110_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailor',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='tailor',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.nameFile),
        ),
        migrations.AddField(
            model_name='tailor',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
