# Generated by Django 2.2.7 on 2019-11-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20191110_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
        migrations.AddField(
            model_name='fashiondesigner',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
        migrations.AddField(
            model_name='maggamdesigner',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
        migrations.AddField(
            model_name='master',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
    ]
