# Generated by Django 2.2.7 on 2019-11-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191110_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.File'),
        ),
    ]
