# Generated by Django 2.2.7 on 2019-11-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='images',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='fashiondesigner',
            name='images',
        ),
        migrations.RemoveField(
            model_name='maggamdesigner',
            name='images',
        ),
        migrations.RemoveField(
            model_name='master',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='images',
        ),
    ]
